-- Centro Universitario Moctezuma
-- Soporte para movimientos académicos auditables (modalidad/cuatrimestre).
-- Equivalente a la migración 2026_09_04_000001_create_movimientos_academicos_table.php

CREATE TABLE IF NOT EXISTS `movimientos_academicos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `lote` varchar(40) NOT NULL,
  `tipo` varchar(40) NOT NULL,
  `inscripcion_id` bigint unsigned DEFAULT NULL,
  `matricula_snapshot` varchar(20) DEFAULT NULL,
  `alumno_snapshot` varchar(180) DEFAULT NULL,
  `licenciatura_id` bigint unsigned DEFAULT NULL,
  `generacion_id` bigint unsigned DEFAULT NULL,
  `modalidad_origen_id` bigint unsigned DEFAULT NULL,
  `modalidad_destino_id` bigint unsigned DEFAULT NULL,
  `cuatrimestre_origen_id` bigint unsigned DEFAULT NULL,
  `cuatrimestre_destino_id` bigint unsigned DEFAULT NULL,
  `motivo` varchar(60) NOT NULL,
  `observaciones` text DEFAULT NULL,
  `calificaciones_trasladadas` int unsigned NOT NULL DEFAULT 0,
  `estado` varchar(20) NOT NULL DEFAULT 'aplicado',
  `ejecutado_por` bigint unsigned DEFAULT NULL,
  `revertido_por` bigint unsigned DEFAULT NULL,
  `revertido_at` timestamp NULL DEFAULT NULL,
  `detalles` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `movimientos_academicos_lote_index` (`lote`),
  KEY `mov_acad_inscripcion_fecha_idx` (`inscripcion_id`,`created_at`),
  KEY `mov_acad_contexto_tipo_idx` (`licenciatura_id`,`generacion_id`,`tipo`),
  KEY `mov_acad_lote_estado_idx` (`lote`,`estado`),
  KEY `mov_acad_licenciatura_fk` (`licenciatura_id`),
  KEY `mov_acad_generacion_fk` (`generacion_id`),
  KEY `mov_acad_modalidad_origen_fk` (`modalidad_origen_id`),
  KEY `mov_acad_modalidad_destino_fk` (`modalidad_destino_id`),
  KEY `mov_acad_cuatrimestre_origen_fk` (`cuatrimestre_origen_id`),
  KEY `mov_acad_cuatrimestre_destino_fk` (`cuatrimestre_destino_id`),
  KEY `mov_acad_ejecutado_por_fk` (`ejecutado_por`),
  KEY `mov_acad_revertido_por_fk` (`revertido_por`),
  CONSTRAINT `mov_acad_inscripcion_fk` FOREIGN KEY (`inscripcion_id`) REFERENCES `inscripciones` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_licenciatura_fk` FOREIGN KEY (`licenciatura_id`) REFERENCES `licenciaturas` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_generacion_fk` FOREIGN KEY (`generacion_id`) REFERENCES `generaciones` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_modalidad_origen_fk` FOREIGN KEY (`modalidad_origen_id`) REFERENCES `modalidades` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_modalidad_destino_fk` FOREIGN KEY (`modalidad_destino_id`) REFERENCES `modalidades` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_cuatrimestre_origen_fk` FOREIGN KEY (`cuatrimestre_origen_id`) REFERENCES `cuatrimestres` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_cuatrimestre_destino_fk` FOREIGN KEY (`cuatrimestre_destino_id`) REFERENCES `cuatrimestres` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_ejecutado_por_fk` FOREIGN KEY (`ejecutado_por`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `mov_acad_revertido_por_fk` FOREIGN KEY (`revertido_por`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
